version: '3.8'

services:

  mongo:
    image: mongo:4.4
    container_name: my-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Ankara06
    volumes:
      - mongo_data:/data/db
    networks:
      - vbo

  mongo-express:
    image: mongo-express:0.54.0
    container_name: my-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ankara06
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin :Ankara06@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: dataops
      ME_CONFIG_BASICAUTH_PASSWORD: Ankara06
    networks:
      - vbo
volumes:
  mongo_data:
networks:
  vbo:
